typography_spectrum: 0.59858
color:
  brandColors:
    - '#FFCE06'
    - '#F4C505'
    - '#151513'
    - '#CAA21C'
    - '#FFE900'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: NamNamBulu
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Booking
    url: 'http://www.contribe.de'
    type: external
favicon: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: NamNamBulu
purpose: []
