name: NamNamBulu
favicon: null
layout_spectrum: 0.8519876
typography_spectrum: 0.3972431
title: NamNamBulu
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFCE06'
    - '#171715'
    - '#866E10'
  brandStrength: 0.5055377
  lightness: 0.1917293
  saturation: 0.8671679
  rhythmicContrast: 0.5626566
purpose: []
