title: NamNamBulu
cta:
  version: null
  bucket: null
  domain: null
layout_spectrum: 0.2224311
favicon: null
name: NamNamBulu
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.9498747
  lightness: 0.7011278
  saturation: 0.6008772
  rhythmicContrast: 0.8684211
  brandColors:
    - '#FFCE06'
    - '#F4C505'
    - '#151513'
    - '#CAA21C'
    - '#FFE900'
typography_spectrum: 0.89599
