title: NamNamBulu
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 1
favicon: null
name: NamNamBulu
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.9692982
  lightness: 0.7011278
  saturation: 0.6008772
  rhythmicContrast: 0.8684211
  brandColors:
    - '#FFCE06'
    - '#171715'
    - '#866E10'
typography_spectrum: 0.6497494
