layout_spectrum: 0.8519876
typography_spectrum: 0.3972431
color:
  lightness: 0.554463
  brandStrength: 0.5055377
  saturation: 0.8378189
  rhythmicContrast: 0.1756673
  brandColors:
    - '#FFCE06'
    - '#171715'
    - '#866E10'
name: NamNamBulu
